title: Prabhat Sharma
description: I have 7 years of experience having worked in web development domain based on Dot Net and SQL. Worked on RPA projects using UI Path and WorkFusion. Later on, worked as a Full Stack developer using Angular and Dot Net Core and worked on Automation projects using Web APIs. Currently learning and gaining experience in Machine Learning and Deep Learning.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
